version: '3.8'

services:
  api-ia:
    build: .
    container_name: api-ia-fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  yolo-api:
    build:
      context: ./yolo_server
    ports:
      - "8001:8000"
    container_name: yolo-api
    restart: unless-stopped
