version: '3.8'

services:
  ai-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ai-api-unified
    hostname: ai-api
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - YOLO_API_URL=http://yolo-api:8000
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    networks:
      - ai-network
    depends_on:
      - yolo-api
    restart: unless-stopped

  yolo-api:
    build:
      context: ./yolo_server
      dockerfile: Dockerfile
    container_name: yolo-api-server
    hostname: yolo-api
    ports:
      - "8002:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./models:/app/models
    networks:
      - ai-network
    restart: unless-stopped

networks:
  ai-network:
    external: true
    name: hadoop-net  # Connecté au réseau Hadoop