version: '3.8'

services:
  # ============ API IA UNIFIÉE ============
  ai-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ai-api-unified
    hostname: ai-api
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - YOLO_API_URL=http://yolo-api:8000  # URL interne reste 8000
    volumes:
      - ./models:/app/models  # Modèles persistants
      - ./logs:/app/logs      # Logs persistants
    networks:
      - ai-network
    depends_on:
      - yolo-api
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # ============ API YOLO SPÉCIALISÉE ============
  yolo-api:
    build:
      context: ./yolo_server
      dockerfile: Dockerfile
    container_name: yolo-api-server
    hostname: yolo-api
    ports:
      - "8002:8000"  # Port externe différent pour éviter conflit
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./models:/app/models
    networks:
      - ai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# ============ VOLUMES PERSISTANTS ============
volumes:
  models_data:
    driver: local
  logs_data:
    driver: local

# ============ RÉSEAU ============
networks:
  ai-network:
    driver: bridge